package playground

import (
	"bufio"
	"embed"
	"fmt"
	"strings"
	"sync"
)

// _modules holds Go-module-proxy-format zips of the third-party packages used
// by the remote-import samples (uuid.go, errors1.go), plus a "modules.txt"
// manifest of "<path> <version>" lines. It is generated by the Makefile
// (gitignored, like _samples) and embedded so those imports resolve with no
// network access -- see wireFS in setup.go.
//
//go:embed _modules
var modulesFS embed.FS

// Module is a bundled third-party module: its import path, version, and the
// proxy-format zip bytes ready for modfs.Inject.
type Module struct {
	Path    string
	Version string
	Zip     []byte
}

var bundledModulesOnce = sync.OnceValue(loadBundledModules)

// bundledModules returns the embedded third-party modules.
func bundledModules() []Module { return bundledModulesOnce() }

func loadBundledModules() []Module {
	f, err := modulesFS.Open("_modules/modules.txt")
	if err != nil {
		return nil
	}
	defer f.Close() //nolint:errcheck

	var mods []Module
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) != 2 {
			continue
		}
		path, version := fields[0], fields[1]
		name := fmt.Sprintf("%s@%s.zip", strings.ReplaceAll(path, "/", "-"), version)
		data, err := modulesFS.ReadFile("_modules/" + name)
		if err != nil {
			continue
		}
		mods = append(mods, Module{Path: path, Version: version, Zip: data})
	}
	return mods
}
